// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaTh7MVDGUKdCSNSajUfkXufyZz5EtOw4',
    appId: '1:503874722566:web:64f05a8df5424df5d11c87',
    messagingSenderId: '503874722566',
    projectId: 'e-tournament-app-95b12',
    authDomain: 'e-tournament-app-95b12.firebaseapp.com',
    storageBucket: 'e-tournament-app-95b12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9fK5cNzQ6dzSnBN7EJfTBrTd2QrJIKc',
    appId: '1:503874722566:android:3f5d3e07229d394ed11c87',
    messagingSenderId: '503874722566',
    projectId: 'e-tournament-app-95b12',
    storageBucket: 'e-tournament-app-95b12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwElmTfsBW3OfyLpPTfmcereGdrYZRKc',
    appId: '1:503874722566:ios:b7e7386e52fe643cd11c87',
    messagingSenderId: '503874722566',
    projectId: 'e-tournament-app-95b12',
    storageBucket: 'e-tournament-app-95b12.firebasestorage.app',
    iosBundleId: 'com.example.eTournamentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVwElmTfsBW3OfyLpPTfmcereGdrYZRKc',
    appId: '1:503874722566:ios:b7e7386e52fe643cd11c87',
    messagingSenderId: '503874722566',
    projectId: 'e-tournament-app-95b12',
    storageBucket: 'e-tournament-app-95b12.firebasestorage.app',
    iosBundleId: 'com.example.eTournamentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaTh7MVDGUKdCSNSajUfkXufyZz5EtOw4',
    appId: '1:503874722566:web:859a1aeae9a6ffdcd11c87',
    messagingSenderId: '503874722566',
    projectId: 'e-tournament-app-95b12',
    authDomain: 'e-tournament-app-95b12.firebaseapp.com',
    storageBucket: 'e-tournament-app-95b12.firebasestorage.app',
  );

}